/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationError
 */
export interface AuthenticationError {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationError
     */
    message: string;
}

/**
 * Check if a given object implements the AuthenticationError interface.
 */
export function instanceOfAuthenticationError(value: object): value is AuthenticationError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AuthenticationErrorFromJSON(json: any): AuthenticationError {
    return AuthenticationErrorFromJSONTyped(json, false);
}

export function AuthenticationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AuthenticationErrorToJSON(json: any): AuthenticationError {
    return AuthenticationErrorToJSONTyped(json, false);
}

export function AuthenticationErrorToJSONTyped(value?: AuthenticationError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

