/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConflictError
 */
export interface ConflictError {
    /**
     * 
     * @type {string}
     * @memberof ConflictError
     */
    message: string;
}

/**
 * Check if a given object implements the ConflictError interface.
 */
export function instanceOfConflictError(value: object): value is ConflictError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ConflictErrorFromJSON(json: any): ConflictError {
    return ConflictErrorFromJSONTyped(json, false);
}

export function ConflictErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ConflictErrorToJSON(json: any): ConflictError {
    return ConflictErrorToJSONTyped(json, false);
}

export function ConflictErrorToJSONTyped(value?: ConflictError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

