/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConflictError
 */
export interface ConflictError {
    /**
     * 
     * @type {string}
     * @memberof ConflictError
     */
    message: string;
}

/**
 * Check if a given object implements the ConflictError interface.
 */
export function instanceOfConflictError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ConflictErrorFromJSON(json: any): ConflictError {
    return ConflictErrorFromJSONTyped(json, false);
}

export function ConflictErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ConflictErrorToJSON(value?: ConflictError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

