/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorTest
 */
export interface ErrorTest {
    /**
     * 
     * @type {string}
     * @memberof ErrorTest
     */
    arbitraryString?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorTest
     */
    arbitraryInt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorTest
     */
    forceServerError?: boolean;
}

/**
 * Check if a given object implements the ErrorTest interface.
 */
export function instanceOfErrorTest(value: object): value is ErrorTest {
    return true;
}

export function ErrorTestFromJSON(json: any): ErrorTest {
    return ErrorTestFromJSONTyped(json, false);
}

export function ErrorTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorTest {
    if (json == null) {
        return json;
    }
    return {
        
        'arbitraryString': json['arbitrary_string'] == null ? undefined : json['arbitrary_string'],
        'arbitraryInt': json['arbitrary_int'] == null ? undefined : json['arbitrary_int'],
        'forceServerError': json['force_server_error'] == null ? undefined : json['force_server_error'],
    };
}

export function ErrorTestToJSON(json: any): ErrorTest {
    return ErrorTestToJSONTyped(json, false);
}

export function ErrorTestToJSONTyped(value?: ErrorTest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arbitrary_string': value['arbitraryString'],
        'arbitrary_int': value['arbitraryInt'],
        'force_server_error': value['forceServerError'],
    };
}

