/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorTest
 */
export interface ErrorTest {
    /**
     * 
     * @type {string}
     * @memberof ErrorTest
     */
    arbitraryString?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorTest
     */
    arbitraryInt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorTest
     */
    forceServerError?: boolean;
}

/**
 * Check if a given object implements the ErrorTest interface.
 */
export function instanceOfErrorTest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorTestFromJSON(json: any): ErrorTest {
    return ErrorTestFromJSONTyped(json, false);
}

export function ErrorTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorTest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'arbitraryString': !exists(json, 'arbitrary_string') ? undefined : json['arbitrary_string'],
        'arbitraryInt': !exists(json, 'arbitrary_int') ? undefined : json['arbitrary_int'],
        'forceServerError': !exists(json, 'force_server_error') ? undefined : json['force_server_error'],
    };
}

export function ErrorTestToJSON(value?: ErrorTest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'arbitrary_string': value.arbitraryString,
        'arbitrary_int': value.arbitraryInt,
        'force_server_error': value.forceServerError,
    };
}

