/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormatTranslation } from './FormatTranslation';
import {
    FormatTranslationFromJSON,
    FormatTranslationFromJSONTyped,
    FormatTranslationToJSON,
    FormatTranslationToJSONTyped,
} from './FormatTranslation';

/**
 * 
 * @export
 * @interface FormatPartialUpdate
 */
export interface FormatPartialUpdate {
    /**
     * 
     * @type {string}
     * @memberof FormatPartialUpdate
     */
    worldId?: string;
    /**
     * 
     * @type {string}
     * @memberof FormatPartialUpdate
     */
    type?: string;
    /**
     * 
     * @type {Array<FormatTranslation>}
     * @memberof FormatPartialUpdate
     */
    translations?: Array<FormatTranslation>;
}

/**
 * Check if a given object implements the FormatPartialUpdate interface.
 */
export function instanceOfFormatPartialUpdate(value: object): value is FormatPartialUpdate {
    return true;
}

export function FormatPartialUpdateFromJSON(json: any): FormatPartialUpdate {
    return FormatPartialUpdateFromJSONTyped(json, false);
}

export function FormatPartialUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormatPartialUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'worldId': json['worldId'] == null ? undefined : json['worldId'],
        'type': json['type'] == null ? undefined : json['type'],
        'translations': json['translations'] == null ? undefined : ((json['translations'] as Array<any>).map(FormatTranslationFromJSON)),
    };
}

export function FormatPartialUpdateToJSON(json: any): FormatPartialUpdate {
    return FormatPartialUpdateToJSONTyped(json, false);
}

export function FormatPartialUpdateToJSONTyped(value?: FormatPartialUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'worldId': value['worldId'],
        'type': value['type'],
        'translations': value['translations'] == null ? undefined : ((value['translations'] as Array<any>).map(FormatTranslationToJSON)),
    };
}

