/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeetingChangeResource
 */
export interface MeetingChangeResource {
    /**
     * Human-readable date and time.
     * @type {string}
     * @memberof MeetingChangeResource
     */
    dateString?: string;
    /**
     * Name of the user who made the change.
     * @type {string}
     * @memberof MeetingChangeResource
     */
    userName?: string;
    /**
     * Name of the service body related to the meeting.
     * @type {string}
     * @memberof MeetingChangeResource
     */
    serviceBodyName?: string;
    /**
     * Details about the changes.
     * @type {string}
     * @memberof MeetingChangeResource
     */
    details?: string;
}

/**
 * Check if a given object implements the MeetingChangeResource interface.
 */
export function instanceOfMeetingChangeResource(value: object): value is MeetingChangeResource {
    return true;
}

export function MeetingChangeResourceFromJSON(json: any): MeetingChangeResource {
    return MeetingChangeResourceFromJSONTyped(json, false);
}

export function MeetingChangeResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingChangeResource {
    if (json == null) {
        return json;
    }
    return {
        
        'dateString': json['date_string'] == null ? undefined : json['date_string'],
        'userName': json['user_name'] == null ? undefined : json['user_name'],
        'serviceBodyName': json['service_body_name'] == null ? undefined : json['service_body_name'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

  export function MeetingChangeResourceToJSON(json: any): MeetingChangeResource {
      return MeetingChangeResourceToJSONTyped(json, false);
  }

  export function MeetingChangeResourceToJSONTyped(value?: MeetingChangeResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date_string': value['dateString'],
        'user_name': value['userName'],
        'service_body_name': value['serviceBodyName'],
        'details': value['details'],
    };
}

