/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFoundError
 */
export interface NotFoundError {
    /**
     * 
     * @type {string}
     * @memberof NotFoundError
     */
    message: string;
}

/**
 * Check if a given object implements the NotFoundError interface.
 */
export function instanceOfNotFoundError(value: object): value is NotFoundError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function NotFoundErrorFromJSON(json: any): NotFoundError {
    return NotFoundErrorFromJSONTyped(json, false);
}

export function NotFoundErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function NotFoundErrorToJSON(json: any): NotFoundError {
    return NotFoundErrorToJSONTyped(json, false);
}

export function NotFoundErrorToJSONTyped(value?: NotFoundError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

