/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RootServerBaseStatisticsMeetings
 */
export interface RootServerBaseStatisticsMeetings {
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsMeetings
     */
    numTotal: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsMeetings
     */
    numInPerson: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsMeetings
     */
    numVirtual: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsMeetings
     */
    numHybrid: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsMeetings
     */
    numUnknown: number;
}

/**
 * Check if a given object implements the RootServerBaseStatisticsMeetings interface.
 */
export function instanceOfRootServerBaseStatisticsMeetings(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "numTotal" in value;
    isInstance = isInstance && "numInPerson" in value;
    isInstance = isInstance && "numVirtual" in value;
    isInstance = isInstance && "numHybrid" in value;
    isInstance = isInstance && "numUnknown" in value;

    return isInstance;
}

export function RootServerBaseStatisticsMeetingsFromJSON(json: any): RootServerBaseStatisticsMeetings {
    return RootServerBaseStatisticsMeetingsFromJSONTyped(json, false);
}

export function RootServerBaseStatisticsMeetingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootServerBaseStatisticsMeetings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numTotal': json['numTotal'],
        'numInPerson': json['numInPerson'],
        'numVirtual': json['numVirtual'],
        'numHybrid': json['numHybrid'],
        'numUnknown': json['numUnknown'],
    };
}

export function RootServerBaseStatisticsMeetingsToJSON(value?: RootServerBaseStatisticsMeetings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'numTotal': value.numTotal,
        'numInPerson': value.numInPerson,
        'numVirtual': value.numVirtual,
        'numHybrid': value.numHybrid,
        'numUnknown': value.numUnknown,
    };
}

