/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RootServerBaseStatistics } from './RootServerBaseStatistics';
import {
    RootServerBaseStatisticsFromJSON,
    RootServerBaseStatisticsFromJSONTyped,
    RootServerBaseStatisticsToJSON,
} from './RootServerBaseStatistics';

/**
 * 
 * @export
 * @interface RootServer
 */
export interface RootServer {
    /**
     * 
     * @type {number}
     * @memberof RootServer
     */
    sourceId: number;
    /**
     * 
     * @type {string}
     * @memberof RootServer
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RootServer
     */
    url: string;
    /**
     * 
     * @type {RootServerBaseStatistics}
     * @memberof RootServer
     */
    statistics?: RootServerBaseStatistics;
    /**
     * 
     * @type {string}
     * @memberof RootServer
     */
    serverInfo?: string;
    /**
     * 
     * @type {Date}
     * @memberof RootServer
     */
    lastSuccessfulImport: Date;
    /**
     * 
     * @type {number}
     * @memberof RootServer
     */
    id: number;
}

/**
 * Check if a given object implements the RootServer interface.
 */
export function instanceOfRootServer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sourceId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "lastSuccessfulImport" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function RootServerFromJSON(json: any): RootServer {
    return RootServerFromJSONTyped(json, false);
}

export function RootServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootServer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceId': json['sourceId'],
        'name': json['name'],
        'url': json['url'],
        'statistics': !exists(json, 'statistics') ? undefined : RootServerBaseStatisticsFromJSON(json['statistics']),
        'serverInfo': !exists(json, 'serverInfo') ? undefined : json['serverInfo'],
        'lastSuccessfulImport': (new Date(json['lastSuccessfulImport'])),
        'id': json['id'],
    };
}

export function RootServerToJSON(value?: RootServer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourceId': value.sourceId,
        'name': value.name,
        'url': value.url,
        'statistics': RootServerBaseStatisticsToJSON(value.statistics),
        'serverInfo': value.serverInfo,
        'lastSuccessfulImport': (value.lastSuccessfulImport.toISOString()),
        'id': value.id,
    };
}

