/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RootServerBaseStatisticsMeetings } from './RootServerBaseStatisticsMeetings';
import {
    RootServerBaseStatisticsMeetingsFromJSON,
    RootServerBaseStatisticsMeetingsFromJSONTyped,
    RootServerBaseStatisticsMeetingsToJSON,
    RootServerBaseStatisticsMeetingsToJSONTyped,
} from './RootServerBaseStatisticsMeetings';
import type { RootServerBaseStatisticsServiceBodies } from './RootServerBaseStatisticsServiceBodies';
import {
    RootServerBaseStatisticsServiceBodiesFromJSON,
    RootServerBaseStatisticsServiceBodiesFromJSONTyped,
    RootServerBaseStatisticsServiceBodiesToJSON,
    RootServerBaseStatisticsServiceBodiesToJSONTyped,
} from './RootServerBaseStatisticsServiceBodies';

/**
 * 
 * @export
 * @interface RootServerBaseStatistics
 */
export interface RootServerBaseStatistics {
    /**
     * 
     * @type {RootServerBaseStatisticsServiceBodies}
     * @memberof RootServerBaseStatistics
     */
    serviceBodies: RootServerBaseStatisticsServiceBodies;
    /**
     * 
     * @type {RootServerBaseStatisticsMeetings}
     * @memberof RootServerBaseStatistics
     */
    meetings: RootServerBaseStatisticsMeetings;
}

/**
 * Check if a given object implements the RootServerBaseStatistics interface.
 */
export function instanceOfRootServerBaseStatistics(value: object): value is RootServerBaseStatistics {
    if (!('serviceBodies' in value) || value['serviceBodies'] === undefined) return false;
    if (!('meetings' in value) || value['meetings'] === undefined) return false;
    return true;
}

export function RootServerBaseStatisticsFromJSON(json: any): RootServerBaseStatistics {
    return RootServerBaseStatisticsFromJSONTyped(json, false);
}

export function RootServerBaseStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootServerBaseStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceBodies': RootServerBaseStatisticsServiceBodiesFromJSON(json['serviceBodies']),
        'meetings': RootServerBaseStatisticsMeetingsFromJSON(json['meetings']),
    };
}

export function RootServerBaseStatisticsToJSON(json: any): RootServerBaseStatistics {
    return RootServerBaseStatisticsToJSONTyped(json, false);
}

export function RootServerBaseStatisticsToJSONTyped(value?: RootServerBaseStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceBodies': RootServerBaseStatisticsServiceBodiesToJSON(value['serviceBodies']),
        'meetings': RootServerBaseStatisticsMeetingsToJSON(value['meetings']),
    };
}

