/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RootServerBaseStatisticsServiceBodies
 */
export interface RootServerBaseStatisticsServiceBodies {
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsServiceBodies
     */
    numZones: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsServiceBodies
     */
    numRegions: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsServiceBodies
     */
    numAreas: number;
    /**
     * 
     * @type {number}
     * @memberof RootServerBaseStatisticsServiceBodies
     */
    numGroups: number;
}

/**
 * Check if a given object implements the RootServerBaseStatisticsServiceBodies interface.
 */
export function instanceOfRootServerBaseStatisticsServiceBodies(value: object): value is RootServerBaseStatisticsServiceBodies {
    if (!('numZones' in value) || value['numZones'] === undefined) return false;
    if (!('numRegions' in value) || value['numRegions'] === undefined) return false;
    if (!('numAreas' in value) || value['numAreas'] === undefined) return false;
    if (!('numGroups' in value) || value['numGroups'] === undefined) return false;
    return true;
}

export function RootServerBaseStatisticsServiceBodiesFromJSON(json: any): RootServerBaseStatisticsServiceBodies {
    return RootServerBaseStatisticsServiceBodiesFromJSONTyped(json, false);
}

export function RootServerBaseStatisticsServiceBodiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootServerBaseStatisticsServiceBodies {
    if (json == null) {
        return json;
    }
    return {
        
        'numZones': json['numZones'],
        'numRegions': json['numRegions'],
        'numAreas': json['numAreas'],
        'numGroups': json['numGroups'],
    };
}

export function RootServerBaseStatisticsServiceBodiesToJSON(json: any): RootServerBaseStatisticsServiceBodies {
    return RootServerBaseStatisticsServiceBodiesToJSONTyped(json, false);
}

export function RootServerBaseStatisticsServiceBodiesToJSONTyped(value?: RootServerBaseStatisticsServiceBodies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numZones': value['numZones'],
        'numRegions': value['numRegions'],
        'numAreas': value['numAreas'],
        'numGroups': value['numGroups'],
    };
}

