/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceBodyEditor
 */
export interface ServiceBodyEditor {
    /**
     * 
     * @type {number}
     * @memberof ServiceBodyEditor
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyEditor
     */
    displayName: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceBodyEditor
     */
    readOnly: boolean;
}

/**
 * Check if a given object implements the ServiceBodyEditor interface.
 */
export function instanceOfServiceBodyEditor(value: object): value is ServiceBodyEditor {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('readOnly' in value) || value['readOnly'] === undefined) return false;
    return true;
}

export function ServiceBodyEditorFromJSON(json: any): ServiceBodyEditor {
    return ServiceBodyEditorFromJSONTyped(json, false);
}

export function ServiceBodyEditorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBodyEditor {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'displayName': json['displayName'],
        'readOnly': json['readOnly'],
    };
}

export function ServiceBodyEditorToJSON(json: any): ServiceBodyEditor {
    return ServiceBodyEditorToJSONTyped(json, false);
}

export function ServiceBodyEditorToJSONTyped(value?: ServiceBodyEditor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'displayName': value['displayName'],
        'readOnly': value['readOnly'],
    };
}

