/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerBaseStatisticsServiceBodies
 */
export interface ServerBaseStatisticsServiceBodies {
    /**
     * 
     * @type {number}
     * @memberof ServerBaseStatisticsServiceBodies
     */
    numZones: number;
    /**
     * 
     * @type {number}
     * @memberof ServerBaseStatisticsServiceBodies
     */
    numRegions: number;
    /**
     * 
     * @type {number}
     * @memberof ServerBaseStatisticsServiceBodies
     */
    numAreas: number;
    /**
     * 
     * @type {number}
     * @memberof ServerBaseStatisticsServiceBodies
     */
    numGroups: number;
}

/**
 * Check if a given object implements the ServerBaseStatisticsServiceBodies interface.
 */
export function instanceOfServerBaseStatisticsServiceBodies(value: object): value is ServerBaseStatisticsServiceBodies {
    if (!('numZones' in value) || value['numZones'] === undefined) return false;
    if (!('numRegions' in value) || value['numRegions'] === undefined) return false;
    if (!('numAreas' in value) || value['numAreas'] === undefined) return false;
    if (!('numGroups' in value) || value['numGroups'] === undefined) return false;
    return true;
}

export function ServerBaseStatisticsServiceBodiesFromJSON(json: any): ServerBaseStatisticsServiceBodies {
    return ServerBaseStatisticsServiceBodiesFromJSONTyped(json, false);
}

export function ServerBaseStatisticsServiceBodiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerBaseStatisticsServiceBodies {
    if (json == null) {
        return json;
    }
    return {
        
        'numZones': json['numZones'],
        'numRegions': json['numRegions'],
        'numAreas': json['numAreas'],
        'numGroups': json['numGroups'],
    };
}

export function ServerBaseStatisticsServiceBodiesToJSON(json: any): ServerBaseStatisticsServiceBodies {
    return ServerBaseStatisticsServiceBodiesToJSONTyped(json, false);
}

export function ServerBaseStatisticsServiceBodiesToJSONTyped(value?: ServerBaseStatisticsServiceBodies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numZones': value['numZones'],
        'numRegions': value['numRegions'],
        'numAreas': value['numAreas'],
        'numGroups': value['numGroups'],
    };
}

