/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerBaseStatistics } from './ServerBaseStatistics';
import {
    ServerBaseStatisticsFromJSON,
    ServerBaseStatisticsFromJSONTyped,
    ServerBaseStatisticsToJSON,
    ServerBaseStatisticsToJSONTyped,
} from './ServerBaseStatistics';

/**
 * 
 * @export
 * @interface Server
 */
export interface Server {
    /**
     * 
     * @type {number}
     * @memberof Server
     */
    sourceId: number;
    /**
     * 
     * @type {string}
     * @memberof Server
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Server
     */
    url: string;
    /**
     * 
     * @type {ServerBaseStatistics}
     * @memberof Server
     */
    statistics?: ServerBaseStatistics;
    /**
     * 
     * @type {string}
     * @memberof Server
     */
    serverInfo?: string;
    /**
     * 
     * @type {Date}
     * @memberof Server
     */
    lastSuccessfulImport: Date;
    /**
     * 
     * @type {number}
     * @memberof Server
     */
    id: number;
}

/**
 * Check if a given object implements the Server interface.
 */
export function instanceOfServer(value: object): value is Server {
    if (!('sourceId' in value) || value['sourceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('lastSuccessfulImport' in value) || value['lastSuccessfulImport'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ServerFromJSON(json: any): Server {
    return ServerFromJSONTyped(json, false);
}

export function ServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Server {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceId': json['sourceId'],
        'name': json['name'],
        'url': json['url'],
        'statistics': json['statistics'] == null ? undefined : ServerBaseStatisticsFromJSON(json['statistics']),
        'serverInfo': json['serverInfo'] == null ? undefined : json['serverInfo'],
        'lastSuccessfulImport': (new Date(json['lastSuccessfulImport'])),
        'id': json['id'],
    };
}

export function ServerToJSON(json: any): Server {
    return ServerToJSONTyped(json, false);
}

export function ServerToJSONTyped(value?: Server | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceId': value['sourceId'],
        'name': value['name'],
        'url': value['url'],
        'statistics': ServerBaseStatisticsToJSON(value['statistics']),
        'serverInfo': value['serverInfo'],
        'lastSuccessfulImport': ((value['lastSuccessfulImport']).toISOString()),
        'id': value['id'],
    };
}

