/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerBaseStatisticsServiceBodies } from './ServerBaseStatisticsServiceBodies';
import {
    ServerBaseStatisticsServiceBodiesFromJSON,
    ServerBaseStatisticsServiceBodiesFromJSONTyped,
    ServerBaseStatisticsServiceBodiesToJSON,
    ServerBaseStatisticsServiceBodiesToJSONTyped,
} from './ServerBaseStatisticsServiceBodies';
import type { ServerBaseStatisticsMeetings } from './ServerBaseStatisticsMeetings';
import {
    ServerBaseStatisticsMeetingsFromJSON,
    ServerBaseStatisticsMeetingsFromJSONTyped,
    ServerBaseStatisticsMeetingsToJSON,
    ServerBaseStatisticsMeetingsToJSONTyped,
} from './ServerBaseStatisticsMeetings';

/**
 * 
 * @export
 * @interface ServerBaseStatistics
 */
export interface ServerBaseStatistics {
    /**
     * 
     * @type {ServerBaseStatisticsServiceBodies}
     * @memberof ServerBaseStatistics
     */
    serviceBodies: ServerBaseStatisticsServiceBodies;
    /**
     * 
     * @type {ServerBaseStatisticsMeetings}
     * @memberof ServerBaseStatistics
     */
    meetings: ServerBaseStatisticsMeetings;
}

/**
 * Check if a given object implements the ServerBaseStatistics interface.
 */
export function instanceOfServerBaseStatistics(value: object): value is ServerBaseStatistics {
    if (!('serviceBodies' in value) || value['serviceBodies'] === undefined) return false;
    if (!('meetings' in value) || value['meetings'] === undefined) return false;
    return true;
}

export function ServerBaseStatisticsFromJSON(json: any): ServerBaseStatistics {
    return ServerBaseStatisticsFromJSONTyped(json, false);
}

export function ServerBaseStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerBaseStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceBodies': ServerBaseStatisticsServiceBodiesFromJSON(json['serviceBodies']),
        'meetings': ServerBaseStatisticsMeetingsFromJSON(json['meetings']),
    };
}

export function ServerBaseStatisticsToJSON(json: any): ServerBaseStatistics {
    return ServerBaseStatisticsToJSONTyped(json, false);
}

export function ServerBaseStatisticsToJSONTyped(value?: ServerBaseStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceBodies': ServerBaseStatisticsServiceBodiesToJSON(value['serviceBodies']),
        'meetings': ServerBaseStatisticsMeetingsToJSON(value['meetings']),
    };
}

