/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceBodyPartialUpdate
 */
export interface ServiceBodyPartialUpdate {
    /**
     * 
     * @type {number}
     * @memberof ServiceBodyPartialUpdate
     */
    parentId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceBodyPartialUpdate
     */
    adminUserId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceBodyPartialUpdate
     */
    assignedUserIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    helpline?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyPartialUpdate
     */
    worldId?: string;
}

/**
 * Check if a given object implements the ServiceBodyPartialUpdate interface.
 */
export function instanceOfServiceBodyPartialUpdate(value: object): value is ServiceBodyPartialUpdate {
    return true;
}

export function ServiceBodyPartialUpdateFromJSON(json: any): ServiceBodyPartialUpdate {
    return ServiceBodyPartialUpdateFromJSONTyped(json, false);
}

export function ServiceBodyPartialUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBodyPartialUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'adminUserId': json['adminUserId'] == null ? undefined : json['adminUserId'],
        'assignedUserIds': json['assignedUserIds'] == null ? undefined : json['assignedUserIds'],
        'url': json['url'] == null ? undefined : json['url'],
        'helpline': json['helpline'] == null ? undefined : json['helpline'],
        'email': json['email'] == null ? undefined : json['email'],
        'worldId': json['worldId'] == null ? undefined : json['worldId'],
    };
}

export function ServiceBodyPartialUpdateToJSON(json: any): ServiceBodyPartialUpdate {
    return ServiceBodyPartialUpdateToJSONTyped(json, false);
}

export function ServiceBodyPartialUpdateToJSONTyped(value?: ServiceBodyPartialUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentId': value['parentId'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'adminUserId': value['adminUserId'],
        'assignedUserIds': value['assignedUserIds'],
        'url': value['url'],
        'helpline': value['helpline'],
        'email': value['email'],
        'worldId': value['worldId'],
    };
}

