/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerBaseStatistics } from './ServerBaseStatistics';
import {
    ServerBaseStatisticsFromJSON,
    ServerBaseStatisticsFromJSONTyped,
    ServerBaseStatisticsToJSON,
    ServerBaseStatisticsToJSONTyped,
} from './ServerBaseStatistics';

/**
 * 
 * @export
 * @interface ServerBase
 */
export interface ServerBase {
    /**
     * 
     * @type {number}
     * @memberof ServerBase
     */
    sourceId?: number;
    /**
     * 
     * @type {string}
     * @memberof ServerBase
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerBase
     */
    url?: string;
    /**
     * 
     * @type {ServerBaseStatistics}
     * @memberof ServerBase
     */
    statistics?: ServerBaseStatistics;
    /**
     * 
     * @type {string}
     * @memberof ServerBase
     */
    serverInfo?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServerBase
     */
    lastSuccessfulImport?: Date;
}

/**
 * Check if a given object implements the ServerBase interface.
 */
export function instanceOfServerBase(value: object): value is ServerBase {
    return true;
}

export function ServerBaseFromJSON(json: any): ServerBase {
    return ServerBaseFromJSONTyped(json, false);
}

export function ServerBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerBase {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'statistics': json['statistics'] == null ? undefined : ServerBaseStatisticsFromJSON(json['statistics']),
        'serverInfo': json['serverInfo'] == null ? undefined : json['serverInfo'],
        'lastSuccessfulImport': json['lastSuccessfulImport'] == null ? undefined : (new Date(json['lastSuccessfulImport'])),
    };
}

export function ServerBaseToJSON(json: any): ServerBase {
    return ServerBaseToJSONTyped(json, false);
}

export function ServerBaseToJSONTyped(value?: ServerBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceId': value['sourceId'],
        'name': value['name'],
        'url': value['url'],
        'statistics': ServerBaseStatisticsToJSON(value['statistics']),
        'serverInfo': value['serverInfo'],
        'lastSuccessfulImport': value['lastSuccessfulImport'] == null ? undefined : ((value['lastSuccessfulImport']).toISOString()),
    };
}

