/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceBody
 */
export interface ServiceBody {
    /**
     * 
     * @type {number}
     * @memberof ServiceBody
     */
    parentId: number | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceBody
     */
    adminUserId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceBody
     */
    assignedUserIds: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    helpline: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    worldId: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceBody
     */
    id: number;
}

/**
 * Check if a given object implements the ServiceBody interface.
 */
export function instanceOfServiceBody(value: object): value is ServiceBody {
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('adminUserId' in value) || value['adminUserId'] === undefined) return false;
    if (!('assignedUserIds' in value) || value['assignedUserIds'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('helpline' in value) || value['helpline'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('worldId' in value) || value['worldId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ServiceBodyFromJSON(json: any): ServiceBody {
    return ServiceBodyFromJSONTyped(json, false);
}

export function ServiceBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBody {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'],
        'name': json['name'],
        'description': json['description'],
        'type': json['type'],
        'adminUserId': json['adminUserId'],
        'assignedUserIds': json['assignedUserIds'],
        'url': json['url'],
        'helpline': json['helpline'],
        'email': json['email'],
        'worldId': json['worldId'],
        'id': json['id'],
    };
}

export function ServiceBodyToJSON(json: any): ServiceBody {
    return ServiceBodyToJSONTyped(json, false);
}

export function ServiceBodyToJSONTyped(value?: ServiceBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentId': value['parentId'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'adminUserId': value['adminUserId'],
        'assignedUserIds': value['assignedUserIds'],
        'url': value['url'],
        'helpline': value['helpline'],
        'email': value['email'],
        'worldId': value['worldId'],
        'id': value['id'],
    };
}

