/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceBody
 */
export interface ServiceBody {
    /**
     * 
     * @type {number}
     * @memberof ServiceBody
     */
    parentId: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceBody
     */
    adminUserId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceBody
     */
    assignedUserIds: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    helpline: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBody
     */
    worldId: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceBody
     */
    id: number;
}

/**
 * Check if a given object implements the ServiceBody interface.
 */
export function instanceOfServiceBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "parentId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "adminUserId" in value;
    isInstance = isInstance && "assignedUserIds" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "helpline" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "worldId" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ServiceBodyFromJSON(json: any): ServiceBody {
    return ServiceBodyFromJSONTyped(json, false);
}

export function ServiceBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentId': json['parentId'],
        'name': json['name'],
        'description': json['description'],
        'type': json['type'],
        'adminUserId': json['adminUserId'],
        'assignedUserIds': json['assignedUserIds'],
        'url': json['url'],
        'helpline': json['helpline'],
        'email': json['email'],
        'worldId': json['worldId'],
        'id': json['id'],
    };
}

export function ServiceBodyToJSON(value?: ServiceBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parentId': value.parentId,
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'adminUserId': value.adminUserId,
        'assignedUserIds': value.assignedUserIds,
        'url': value.url,
        'helpline': value.helpline,
        'email': value.email,
        'worldId': value.worldId,
        'id': value.id,
    };
}

