/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsObject
 */
export interface SettingsObject {
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    googleApiKey?: string;
    /**
     * 
     * @type {number}
     * @memberof SettingsObject
     */
    changeDepthForMeetings?: number;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    defaultSortKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    defaultDurationTime?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    regionBias?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    distanceUnits?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    enableEmailContact?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    includeServiceBodyAdminOnEmails?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SettingsObject
     */
    meetingStatesAndProvinces?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SettingsObject
     */
    meetingCountiesAndSubProvinces?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SettingsObject
     */
    searchSpecMapCenterLongitude?: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsObject
     */
    searchSpecMapCenterLatitude?: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsObject
     */
    searchSpecMapCenterZoom?: number;
    /**
     * 
     * @type {number}
     * @memberof SettingsObject
     */
    numberOfMeetingsForAuto?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    autoGeocodingEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    countyAutoGeocodingEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    zipAutoGeocodingEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    defaultClosedStatus?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    enableLanguageSelector?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    aggregatorModeEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingsObject
     */
    aggregatorMaxGeoWidthKm?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SettingsObject
     */
    includeServiceBodyEmailInSemantic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    bmltTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsObject
     */
    bmltNotice?: string;
    /**
     * 
     * @type {object}
     * @memberof SettingsObject
     */
    formatLangNames?: object;
}

/**
 * Check if a given object implements the SettingsObject interface.
 */
export function instanceOfSettingsObject(value: object): value is SettingsObject {
    return true;
}

export function SettingsObjectFromJSON(json: any): SettingsObject {
    return SettingsObjectFromJSONTyped(json, false);
}

export function SettingsObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsObject {
    if (json == null) {
        return json;
    }
    return {
        
        'googleApiKey': json['googleApiKey'] == null ? undefined : json['googleApiKey'],
        'changeDepthForMeetings': json['changeDepthForMeetings'] == null ? undefined : json['changeDepthForMeetings'],
        'defaultSortKey': json['defaultSortKey'] == null ? undefined : json['defaultSortKey'],
        'language': json['language'] == null ? undefined : json['language'],
        'defaultDurationTime': json['defaultDurationTime'] == null ? undefined : json['defaultDurationTime'],
        'regionBias': json['regionBias'] == null ? undefined : json['regionBias'],
        'distanceUnits': json['distanceUnits'] == null ? undefined : json['distanceUnits'],
        'enableEmailContact': json['enableEmailContact'] == null ? undefined : json['enableEmailContact'],
        'includeServiceBodyAdminOnEmails': json['includeServiceBodyAdminOnEmails'] == null ? undefined : json['includeServiceBodyAdminOnEmails'],
        'meetingStatesAndProvinces': json['meetingStatesAndProvinces'] == null ? undefined : json['meetingStatesAndProvinces'],
        'meetingCountiesAndSubProvinces': json['meetingCountiesAndSubProvinces'] == null ? undefined : json['meetingCountiesAndSubProvinces'],
        'searchSpecMapCenterLongitude': json['searchSpecMapCenterLongitude'] == null ? undefined : json['searchSpecMapCenterLongitude'],
        'searchSpecMapCenterLatitude': json['searchSpecMapCenterLatitude'] == null ? undefined : json['searchSpecMapCenterLatitude'],
        'searchSpecMapCenterZoom': json['searchSpecMapCenterZoom'] == null ? undefined : json['searchSpecMapCenterZoom'],
        'numberOfMeetingsForAuto': json['numberOfMeetingsForAuto'] == null ? undefined : json['numberOfMeetingsForAuto'],
        'autoGeocodingEnabled': json['autoGeocodingEnabled'] == null ? undefined : json['autoGeocodingEnabled'],
        'countyAutoGeocodingEnabled': json['countyAutoGeocodingEnabled'] == null ? undefined : json['countyAutoGeocodingEnabled'],
        'zipAutoGeocodingEnabled': json['zipAutoGeocodingEnabled'] == null ? undefined : json['zipAutoGeocodingEnabled'],
        'defaultClosedStatus': json['defaultClosedStatus'] == null ? undefined : json['defaultClosedStatus'],
        'enableLanguageSelector': json['enableLanguageSelector'] == null ? undefined : json['enableLanguageSelector'],
        'aggregatorModeEnabled': json['aggregatorModeEnabled'] == null ? undefined : json['aggregatorModeEnabled'],
        'aggregatorMaxGeoWidthKm': json['aggregatorMaxGeoWidthKm'] == null ? undefined : json['aggregatorMaxGeoWidthKm'],
        'includeServiceBodyEmailInSemantic': json['includeServiceBodyEmailInSemantic'] == null ? undefined : json['includeServiceBodyEmailInSemantic'],
        'bmltTitle': json['bmltTitle'] == null ? undefined : json['bmltTitle'],
        'bmltNotice': json['bmltNotice'] == null ? undefined : json['bmltNotice'],
        'formatLangNames': json['formatLangNames'] == null ? undefined : json['formatLangNames'],
    };
}

export function SettingsObjectToJSON(json: any): SettingsObject {
    return SettingsObjectToJSONTyped(json, false);
}

export function SettingsObjectToJSONTyped(value?: SettingsObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'googleApiKey': value['googleApiKey'],
        'changeDepthForMeetings': value['changeDepthForMeetings'],
        'defaultSortKey': value['defaultSortKey'],
        'language': value['language'],
        'defaultDurationTime': value['defaultDurationTime'],
        'regionBias': value['regionBias'],
        'distanceUnits': value['distanceUnits'],
        'enableEmailContact': value['enableEmailContact'],
        'includeServiceBodyAdminOnEmails': value['includeServiceBodyAdminOnEmails'],
        'meetingStatesAndProvinces': value['meetingStatesAndProvinces'],
        'meetingCountiesAndSubProvinces': value['meetingCountiesAndSubProvinces'],
        'searchSpecMapCenterLongitude': value['searchSpecMapCenterLongitude'],
        'searchSpecMapCenterLatitude': value['searchSpecMapCenterLatitude'],
        'searchSpecMapCenterZoom': value['searchSpecMapCenterZoom'],
        'numberOfMeetingsForAuto': value['numberOfMeetingsForAuto'],
        'autoGeocodingEnabled': value['autoGeocodingEnabled'],
        'countyAutoGeocodingEnabled': value['countyAutoGeocodingEnabled'],
        'zipAutoGeocodingEnabled': value['zipAutoGeocodingEnabled'],
        'defaultClosedStatus': value['defaultClosedStatus'],
        'enableLanguageSelector': value['enableLanguageSelector'],
        'aggregatorModeEnabled': value['aggregatorModeEnabled'],
        'aggregatorMaxGeoWidthKm': value['aggregatorMaxGeoWidthKm'],
        'includeServiceBodyEmailInSemantic': value['includeServiceBodyEmailInSemantic'],
        'bmltTitle': value['bmltTitle'],
        'bmltNotice': value['bmltNotice'],
        'formatLangNames': value['formatLangNames'],
    };
}

